### ISSUE TITLE
Permission Error

### ISSUE THREAD

**Issue by kachapman** [AdnanHodzic/auto-cpufreq#240]
After snap installation, I get this error:

### Error output:
```sudo auto-cpufreq
Traceback (most recent call last):
  File "/snap/auto-cpufreq/71/bin/auto-cpufreq", line 14, in <module>
    from auto_cpufreq.core import *
  File "/snap/auto-cpufreq/71/lib/python3.8/site-packages/auto_cpufreq/core.py", line 66, in <module>
    dist_name = distro.id()
  File "/snap/auto-cpufreq/71/lib/python3.8/site-packages/distro.py", line 204, in id
    return _distro.id()
  File "/snap/auto-cpufreq/71/lib/python3.8/site-packages/distro.py", line 694, in id
    distro_id = self.os_release_attr('id')
  File "/snap/auto-cpufreq/71/lib/python3.8/site-packages/distro.py", line 894, in os_release_attr
    return self._os_release_info.get(attribute, '')
  File "/snap/auto-cpufreq/71/lib/python3.8/site-packages/distro.py", line 556, in __get__
    ret = obj.__dict__[self._fname] = self._f(obj)
  File "/snap/auto-cpufreq/71/lib/python3.8/site-packages/distro.py", line 932, in _os_release_info
    with open(self.os_release_file) as release_file:
PermissionError: [Errno 13] Permission denied: '/etc/os-release'

```
---

### System information:
Pop!OS_21.04
Microsoft Surface Book 2

``auto-cpufreq --debug
Traceback (most recent call last):
  File "/snap/auto-cpufreq/71/bin/auto-cpufreq", line 14, in <module>
    from auto_cpufreq.core import *
  File "/snap/auto-cpufreq/71/lib/python3.8/site-packages/auto_cpufreq/core.py", line 66, in <module>
    dist_name = distro.id()
  File "/snap/auto-cpufreq/71/lib/python3.8/site-packages/distro.py", line 204, in id
    return _distro.id()
  File "/snap/auto-cpufreq/71/lib/python3.8/site-packages/distro.py", line 694, in id
    distro_id = self.os_release_attr('id')
  File "/snap/auto-cpufreq/71/lib/python3.8/site-packages/distro.py", line 894, in os_release_attr
    return self._os_release_info.get(attribute, '')
  File "/snap/auto-cpufreq/71/lib/python3.8/site-packages/distro.py", line 556, in __get__
    ret = obj.__dict__[self._fname] = self._f(obj)
  File "/snap/auto-cpufreq/71/lib/python3.8/site-packages/distro.py", line 932, in _os_release_info
    with open(self.os_release_file) as release_file:
PermissionError: [Errno 13] Permission denied: '/etc/os-release'
```
---

**Comment by urfolomeus** [comment]
I got this error too when installing from Snap on Pop!OS 21.04. I was able to work around by installing with [git instead](https://github.com/AdnanHodzic/auto-cpufreq#auto-cpufreq-installer).
