### ISSUE TITLE
Python version not checked on install

### ISSUE THREAD

**Issue by AokiAhishatsu** [AdnanHodzic/auto-cpufreq#245]
### Error output:
```text
Traceback (most recent call last):
  File "/usr/local/bin/auto-cpufreq", line 4, in <module>
    __import__('pkg_resources').run_script('auto-cpufreq==1.0', 'auto-cpufreq')
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 739, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1501, in run_script
    exec(script_code, namespace, namespace)
  File "/usr/local/lib/python3.5/dist-packages/auto_cpufreq-1.0-py3.5.egg/EGG-INFO/scripts/auto-cpufreq", line 14, in <module>
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 954, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 896, in _find_spec
  File "<frozen importlib._bootstrap_external>", line 1147, in find_spec
  File "<frozen importlib._bootstrap_external>", line 1123, in _get_spec
  File "<frozen importlib._bootstrap_external>", line 1104, in _legacy_get_spec
  File "<frozen importlib._bootstrap>", line 444, in spec_from_loader
  File "<frozen importlib._bootstrap_external>", line 541, in spec_from_file_location
  File "/usr/local/lib/python3.5/dist-packages/auto_cpufreq-1.0-py3.5.egg/auto_cpufreq/core.py", line 159
    ac_info = getoutput(f"grep . {power_dir}A*/online").splitlines()
                                                     ^
SyntaxError: invalid syntax

```
---

### System information:
```text
Tinkerboard S
TinkerOS/Debian 4.4 Kernel
```
---

**Comment by Appocalypze** [comment]
Oke

**Comment by AdnanHodzic** [comment]
Could you install it using [Snap package](https://github.com/AdnanHodzic/auto-cpufreq#snap-store)? As it runs in a container and isolates its Python env from your env. so you shouldn't experience Python related errors.
