### ISSUE TITLE
Won't install on Thinkpad T500 with debian 11 (bullseye)

### ISSUE THREAD

**Issue by thinks222** [AdnanHodzic/auto-cpufreq#407]
hello, i was trying to install this and it won't install at all using `sudo auto-cpufreq --install` and i even tried the solutions for arch based distros if that could even remotely do something 

tried building it myself & using snap to install it and both results end up in failure for no reason at all

i am running a ThinkPad T500 with Libreboot installed ( version 20211122 ) and running stock debian 

i am sorry if i not so descriptive cause i really don't have any idea. 

### Error output:

 user@user:~$ sudo auto-cpufreq --live

Note: You can quit live mode by pressing "ctrl+c"

-------------------------------------------------------------------------------

Traceback (most recent call last):
  File "/opt/auto-cpufreq/venv/bin/auto-cpufreq", line 4, in <module>
    __import__('pkg_resources').run_script('auto-cpufreq==1.9.4+cde4cbeb', 'auto-cpufreq')
  File "/opt/auto-cpufreq/venv/lib/python3.9/site-packages/pkg_resources/__init__.py", line 666, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/opt/auto-cpufreq/venv/lib/python3.9/site-packages/pkg_resources/__init__.py", line 1469, in run_script
    exec(script_code, namespace, namespace)
  File "/opt/auto-cpufreq/venv/lib/python3.9/site-packages/auto_cpufreq-1.9.4+cde4cbeb-py3.9.egg/EGG-INFO/scripts/auto-cpufreq", line 225, in <module>
  File "/opt/auto-cpufreq/venv/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/opt/auto-cpufreq/venv/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/opt/auto-cpufreq/venv/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/auto-cpufreq/venv/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/opt/auto-cpufreq/venv/lib/python3.9/site-packages/auto_cpufreq-1.9.4+cde4cbeb-py3.9.egg/EGG-INFO/scripts/auto-cpufreq", line 119, in main
  File "/opt/auto-cpufreq/venv/lib/python3.9/site-packages/auto_cpufreq-1.9.4+cde4cbeb-py3.9.egg/auto_cpufreq/core.py", line 445, in gov_check
  File "/opt/auto-cpufreq/venv/lib/python3.9/site-packages/auto_cpufreq-1.9.4+cde4cbeb-py3.9.egg/auto_cpufreq/core.py", line 262, in get_avail_gov
  File "/usr/lib/python3.9/pathlib.py", line 1255, in read_text
    with self.open(mode='r', encoding=encoding, errors=errors) as f:
  File "/usr/lib/python3.9/pathlib.py", line 1241, in open
    return io.open(self, mode, buffering, encoding, errors, newline,
  File "/usr/lib/python3.9/pathlib.py", line 1109, in _opener
    return self._accessor.open(self, flags, mode)
FileNotFoundError: [Errno 2] No such file or directory: '/sys/devices/system/cpu/cpu0/cpufreq/scaling_available_governors'
user@user:~$ 

### System information:

Linux distro: Debian GNU/Linux 11 bullseye
Linux kernel: 5.10.0-16-amd64
Processor: Intel(R) Core(TM)2 CPU         T9400  @ 2.53GHz
Cores: 2
Architecture: x86_64

------------------------------ Current CPU stats ------------------------------

CPU max frequency: 0 MHz
CPU min frequency: 0 MHz

Core	Usage	Temperature	Frequency
CPU0:	 13.4%     39 °C     1600 MHz
CPU1:	 14.0%     40 °C     1600 MHz

auto-cpufreq version: 1.9.4 (git: cde4cbeb)

Python: 3.9.2
psutil package: 5.9.1
platform package: 1.0.8
click package: 8.1.3
distro package: 1.7.0

Computer type: Laptop
Battery is: charging

auto-cpufreq system resource consumption:
cpu usage: 0.0 %
memory use: 0.6 %

Total CPU usage: 13.1 %
Total system load: 0.68
Average temp. of all cores: 39.50 °C 

Currently using: cat: governor
Warning: CPU turbo is not available
Currently turbo boost is: off

**Comment by AdnanHodzic** [comment]
Issue template not filled out when creating the issue, hence making it invalid, reference:

### Fill out informtion requested in this template, without doing so issue will be ignored & closed!

### Have you tried?

- [Searching through existing/closed issues](https://github.com/AdnanHodzic/auto-cpufreq/issues) to see if your bug has already been already submitted? 
- If installation failed with [auto-cpufreq-installer](https://github.com/AdnanHodzic/auto-cpufreq/#auto-cpufreq-installer),have you tried installing auto-cpufreq using [Snap package](https://github.com/AdnanHodzic/auto-cpufreq/#snap-store)?
- Have you tried [configuring auto-cpufreq](https://github.com/AdnanHodzic/auto-cpufreq/#configuring-auto-cpufreq)?
- Have you tried suggestions in [troubleshooting section](https://github.com/AdnanHodzic/auto-cpufreq#troubleshooting)?

### Error output:
```text
Add/paste error output in case of failed installation or other failing component
```
---

### System information:

Add/paste output of:

```
auto-cpufreq --debug
```

Also please be descriptive about the issue you're reporting, i.e: what you tried & what's the expected behaviour.

---
