### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'snap'

### ISSUE THREAD

**Issue by WitheRosE901** [AdnanHodzic/auto-cpufreq#482]
### Error output:
```Traceback (most recent call last):
  File "/opt/auto-cpufreq/venv/bin/auto-cpufreq", line 4, in <module>
    __import__('pkg_resources').run_script('auto-cpufreq==1.9.7+dadfae08', 'auto-cpufreq')
  File "/opt/auto-cpufreq/venv/lib/python3.10/site-packages/pkg_resources/__init__.py", line 656, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/opt/auto-cpufreq/venv/lib/python3.10/site-packages/pkg_resources/__init__.py", line 1460, in run_script
    exec(script_code, namespace, namespace)
  File "/opt/auto-cpufreq/venv/lib/python3.10/site-packages/auto_cpufreq-1.9.7+dadfae08-py3.10.egg/EGG-INFO/scripts/auto-cpufreq", line 225, in <module>
  File "/opt/auto-cpufreq/venv/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/opt/auto-cpufreq/venv/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/opt/auto-cpufreq/venv/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/auto-cpufreq/venv/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/opt/auto-cpufreq/venv/lib/python3.10/site-packages/auto_cpufreq-1.9.7+dadfae08-py3.10.egg/EGG-INFO/scripts/auto-cpufreq", line 202, in main
  File "/opt/auto-cpufreq/venv/lib/python3.10/site-packages/auto_cpufreq-1.9.7+dadfae08-py3.10.egg/auto_cpufreq/core.py", line 382, in deploy_daemon
  File "/opt/auto-cpufreq/venv/lib/python3.10/site-packages/auto_cpufreq-1.9.7+dadfae08-py3.10.egg/auto_cpufreq/power_helper.py", line 261, in gnome_power_svc_disable
  File "/usr/lib/python3.10/subprocess.py", line 345, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/usr/lib/python3.10/subprocess.py", line 969, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.10/subprocess.py", line 1845, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'snap'
```
---

### System information:

```
-------------------------------------------------------------------------------

Linux distro: Ubuntu 22.10 Kinetic Kudu
Linux kernel: 5.19.0-29-generic
Processor: Intel(R) Core(TM) i7-5600U CPU @ 2.60GHz
Cores: 4
Architecture: x86_64
Driver: intel_cpufreq

------------------------------ Current CPU stats ------------------------------

CPU max frequency: 2500 MHz
CPU min frequency: 500 MHz

Core	Usage	Temperature	Frequency
CPU0:	  1.0%     48 °C     2500 MHz
CPU1:	  0.0%     47 °C     2497 MHz
CPU2:	  1.0%     48 °C     2500 MHz
CPU3:	  1.0%     47 °C     2500 MHz

CPU fan speed: 0 RPM

auto-cpufreq version: 1.9.7 (git: dadfae08)

Python: 3.10.7
psutil package: 5.9.4
platform package: 1.0.8
click package: 8.1.3
distro package: 1.8.0

Computer type: Laptop
Battery is: charging

auto-cpufreq system resource consumption:
cpu usage: 0.0 %
memory use: 0.29 %

Total CPU usage: 0.5 %
Total system load: 0.25
Average temp. of all cores: 47.50 °C 

Currently using: performance governor
Currently turbo boost is: off

-------------------------------------------------------------------------------
```

### The issue

`--install` failed with this error.

 I use Ubuntu with snap removed so thoroughly that it is basically Debian with GNOME 43. I install this from source, by the way, so I don't see why 'snap' would be involved..

---

**Comment by shadeyg56** [comment]
I just pushed a change to fix this in #481

Please pull the latest commit, run `sudo ./auto-cpufreq-installer --install`, and try again.
