### ISSUE TITLE
Installation Issue

### ISSUE THREAD

**Issue by novtov354** [AdnanHodzic/auto-cpufreq#511]
I am facing a problem after installing using the installer. I always got this:

novan@ThinkPadP53:~/auto-cpufreq$ auto-cpufreq --live
**/opt/auto-cpufreq/venv/bin/python: can't open file '/opt/auto-cpufreq/venv/bin/auto-cpufreq': [Errno 2] No such file or directory**

 Here is the installation process:

> sudo ./auto-cpufreq-installer --install

───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

Detected Debian based distribution

───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

Setting up Python environment

Reading package lists... Done
Building dependency tree       
Reading state information... Done
dmidecode is already the newest version (3.1-1ubuntu0.1).
python3-dev is already the newest version (3.6.7-1~18.04).
python3-setuptools is already the newest version (39.0.1-2ubuntu0.1).
python3-pip is already the newest version (9.0.1-2.3~ubuntu1.18.04.8).
python3-venv is already the newest version (3.6.7-1~18.04).
The following packages were automatically installed and are no longer required:
  apturl-common gir1.2-goa-1.0 gir1.2-snapd-1 gnome-software-common libappstream-glib8 python3-dateutil
  python3-software-properties software-properties-common unattended-upgrades
Use 'sudo apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 256 not upgraded.

Installing necessary Python packages

WARNING: The directory '/home/novan/.cache/pip' or its parent directory is not owned or is not writable by the current user. The cache has been disabled. Check the permissions and owner of that directory. If executing pip with sudo, you should use sudo's -H flag.
Requirement already satisfied: pip in /opt/auto-cpufreq/venv/lib/python3.6/site-packages (21.3.1)
Requirement already satisfied: wheel in /opt/auto-cpufreq/venv/lib/python3.6/site-packages (0.37.1)
WARNING: The directory '/home/novan/.cache/pip' or its parent directory is not owned or is not writable by the current user. The cache has been disabled. Check the permissions and owner of that directory. If executing pip with sudo, you should use sudo's -H flag.
Requirement already satisfied: setuptools in /opt/auto-cpufreq/venv/lib/python3.6/site-packages (from -r requirements.txt (line 1)) (39.0.1)
Requirement already satisfied: psutil in /opt/auto-cpufreq/venv/lib/python3.6/site-packages (from -r requirements.txt (line 2)) (5.9.5)
Requirement already satisfied: click in /opt/auto-cpufreq/venv/lib/python3.6/site-packages (from -r requirements.txt (line 3)) (8.0.4)
Requirement already satisfied: distro in /opt/auto-cpufreq/venv/lib/python3.6/site-packages (from -r requirements.txt (line 4)) (1.8.0)
Requirement already satisfied: importlib-metadata in /opt/auto-cpufreq/venv/lib/python3.6/site-packages (from click->-r requirements.txt (line 3)) (4.8.3)
Requirement already satisfied: zipp>=0.5 in /opt/auto-cpufreq/venv/lib/python3.6/site-packages (from importlib-metadata->click->-r requirements.txt (line 3)) (3.6.0)
Requirement already satisfied: typing-extensions>=3.6.4 in /opt/auto-cpufreq/venv/lib/python3.6/site-packages (from importlib-metadata->click->-r requirements.txt (line 3)) (4.1.1)

───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

installing auto-cpufreq tool

**Traceback (most recent call last):
  File "setup.py", line 43, in <module>
    scripts=["bin/auto-cpufreq"],
  File "/opt/auto-cpufreq/venv/lib/python3.6/site-packages/setuptools/__init__.py", line 129, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib/python3.6/distutils/core.py", line 108, in setup
    _setup_distribution = dist = klass(attrs)
  File "/opt/auto-cpufreq/venv/lib/python3.6/site-packages/setuptools/dist.py", line 372, in __init__
    _Distribution.__init__(self, attrs)
  File "/usr/lib/python3.6/distutils/dist.py", line 281, in __init__
    self.finalize_options()
  File "/opt/auto-cpufreq/venv/lib/python3.6/site-packages/setuptools/dist.py", line 528, in finalize_options
    ep.load()(self, ep.name, value)
  File "/opt/auto-cpufreq/venv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2324, in load
    return self.resolve()
  File "/opt/auto-cpufreq/venv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2330, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/novan/auto-cpufreq/.eggs/setuptools_git_versioning-1.13.3-py3.6.egg/setuptools_git_versioning.py", line 1
    from __future__ import annotations
    ^
SyntaxError: future feature annotations is not defined**

───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

auto-cpufreq tool successfully installed.

For list of options, run:
auto-cpufreq --help"

───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

**Comment by AdnanHodzic** [comment]
Template issue ignored and not filled out, hence making this issue invalid, closing. Feel free to re-open this issue with properly filled out requested fields.

Reference:

### Fill out informtion requested in this template, without doing so issue will be ignored & closed!

### Have you tried?

- [Searching through existing/closed issues](https://github.com/AdnanHodzic/auto-cpufreq/issues) to see if your bug has already been already submitted? 
**- If installation failed with [auto-cpufreq-installer](https://github.com/AdnanHodzic/auto-cpufreq/#auto-cpufreq-installer),have you tried installing auto-cpufreq using [Snap package](https://github.com/AdnanHodzic/auto-cpufreq/#snap-store)?**
- Have you tried [configuring auto-cpufreq](https://github.com/AdnanHodzic/auto-cpufreq/#configuring-auto-cpufreq)?
- Have you tried suggestions in [troubleshooting section](https://github.com/AdnanHodzic/auto-cpufreq#troubleshooting)?

### Error output:
```text
Add/paste error output in case of failed installation or other failing component
```
---

### System information:

Add/paste output of:

```
auto-cpufreq --debug
```

Also please be descriptive about the issue you're reporting, i.e: what you tried & what's the expected behaviour.
