### ISSUE TITLE
Something is preventing auto-cpufreq from reading the thread count of my cpu

### ISSUE THREAD

**Issue by nahpods** [AdnanHodzic/auto-cpufreq#520]
### Error output:
```
Linux distro: Fedora Linux 38 (Workstation Edition)
Linux kernel: 6.3.5-200.fc38.x86_64
Processor: AMD Ryzen 5 4600H with Radeon Graphics
Traceback (most recent call last):
  File "/snap/auto-cpufreq/129/bin/auto-cpufreq", line 225, in <module>
    main()
  File "/snap/auto-cpufreq/129/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/snap/auto-cpufreq/129/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/snap/auto-cpufreq/129/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/snap/auto-cpufreq/129/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/snap/auto-cpufreq/129/bin/auto-cpufreq", line 106, in main
    sysinfo()
  File "/snap/auto-cpufreq/129/lib/python3.10/site-packages/auto_cpufreq/core.py", line 1110, in sysinfo
    total_cpu_count = int(getoutput("nproc"))
ValueError: invalid literal for int() with base 10: "ERROR: ld.so: object '/usr/local/lib64/libinput-config.so' from /etc/ld.so.preload cannot be preloaded (cannot open shared object file): ignored.\nERROR: ld.so: object '/usr/local/lib64/libinput-conf

```
---

### System information:
```
[name@name ~]$ sudo auto-cpufreq --debug
[sudo] password for name: 
ERROR: ld.so: object '/usr/local/lib64/libinput-config.so' from /etc/ld.so.preload cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object '/usr/local/lib64/libinput-config.so' from /etc/ld.so.preload cannot be preloaded (cannot open shared object file): ignored.

-------------------------------------------------------------------------------

Linux distro: Fedora Linux 38 (Workstation Edition)
Linux kernel: 6.3.5-200.fc38.x86_64
Processor: AMD Ryzen 5 4600H with Radeon Graphics
Traceback (most recent call last):
  File "/snap/auto-cpufreq/129/bin/auto-cpufreq", line 225, in <module>
    main()
  File "/snap/auto-cpufreq/129/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/snap/auto-cpufreq/129/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/snap/auto-cpufreq/129/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/snap/auto-cpufreq/129/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/snap/auto-cpufreq/129/bin/auto-cpufreq", line 159, in main
    sysinfo()
  File "/snap/auto-cpufreq/129/lib/python3.10/site-packages/auto_cpufreq/core.py", line 1110, in sysinfo
    total_cpu_count = int(getoutput("nproc"))
ValueError: invalid literal for int() with base 10: "ERROR: ld.so: object '/usr/local/lib64/libinput-config.so' from /etc/ld.so.preload cannot be preloaded (cannot open shared object file): ignored.\nERROR: ld.so: object '/usr/local/lib64/libinput-conf 
```

For some reason my libinput config might not be letting auto-cpufreq run properly. That config is in place for me to reduce my touchpad scrolling speed and I am looking for a way for both of these to work at the same time. The problem with it is that it used to work fine, until one day I got an error that I pasted above. I followed these instructions to reduce my touchpad scrolling speed: https://gitlab.com/warningnonpotablewater/libinput-config. 
I do not have tlp, but I re-enabled daemon power profiles to atleast have some power management until I am able to fix this issue. As I can see from this error, it also cannot for some reason read the thread count of my cpu, so it just crashes. 

I tried: 
- Updating auto-cpufreq
- Reinstalling auto-cpufreq
- Reinstalling coreutils
- Clearing LD_PRELOAD environment variable (```export LD_PRELOAD=```)

---

**Comment by AdnanHodzic** [comment]
Can same fix which was used in #464 be used here?
