### ISSUE TITLE
auto-cpufreq-installer --update fails on Debian trixie/sid leaving NO files behind

### ISSUE THREAD

**Issue by hknox** [AdnanHodzic/auto-cpufreq#555]
### Have you tried?

- [Searching through existing/closed issues](https://github.com/AdnanHodzic/auto-cpufreq/issues) to see if your bug has already been already submitted? 
- If installation failed with [auto-cpufreq-installer](https://github.com/AdnanHodzic/auto-cpufreq/#auto-cpufreq-installer),have you tried installing auto-cpufreq using [Snap package](https://github.com/AdnanHodzic/auto-cpufreq/#snap-store)?
- Have you tried [configuring auto-cpufreq](https://github.com/AdnanHodzic/auto-cpufreq/#configuring-auto-cpufreq)?
- Have you tried suggestions in [troubleshooting section](https://github.com/AdnanHodzic/auto-cpufreq#troubleshooting)?

### Error output:
```st release\n ────────────────────────────────────────────────────────────────────────


--------------------- Removing auto-cpufreq daemon ----------------------

* Turn on bluetooth on boot

----------------------------------- Warning -----------------------------------

Detected GNOME Power Profiles daemon service is stopped!
This service will now be enabled and started again.
* Enabling GNOME power profiles

Unit power-profiles-daemon.service does not exist, proceeding anyway.
Failed to start power-profiles-daemon.service: Unit power-profiles-daemon.service not found.
Failed to enable unit: Unit file power-profiles-daemon.service does not exist.

------------------ Running auto-cpufreq daemon removal script ------------------

* Stopping auto-cpufreq daemon (systemd) service

* Disabling auto-cpufreq daemon (systemd) at boot
Removed "/etc/systemd/system/multi-user.target.wants/auto-cpufreq.service".

* Removing auto-cpufreq daemon (systemd) unit file

* Reloading systemd manager configuration
reset failed

------------------------- auto-cpufreq daemon removed -------------------------

auto-cpufreq successfully removed.

-------------------------------------------------------------------------------



──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────


auto-cpufreq tool and all its supporting files successfully removed.


──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

deleting the current directory

./auto-cpufreq-installer: line 305: cd: too many arguments
cloning to the latest release

fatal: could not create work tree dir 'auto-cpufreq': No such file or directory
./auto-cpufreq-installer: line 309: cd: auto-cpufreq: No such file or directory


──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────



──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────


Detected Debian based distribution


──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────


Setting up Python environment

Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package libgtk-3

Installing necessary Python packages

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/opt/auto-cpufreq/venv/lib/python3.11/site-packages/pip/__main__.py", line 8, in <module>
    if sys.path[0] in ("", os.getcwd()):
                           ^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/opt/auto-cpufreq/venv/lib/python3.11/site-packages/pip/__main__.py", line 8, in <module>
    if sys.path[0] in ("", os.getcwd()):
                           ^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory


──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────


installing auto-cpufreq tool

python3: can't open file 'setup.py': [Errno 2] No such file or directory
cp: cannot stat 'scripts/': No such file or directory
cp: cannot stat 'images/': No such file or directory
cp: cannot stat 'images/icon.png': No such file or directory
cp: cannot stat 'scripts/org.auto-cpufreq.pkexec.policy': No such file or directory
cp: cannot stat 'scripts/auto-cpufreq-venv-wrapper': No such file or directory
cp: cannot stat 'scripts/start_app': No such file or directory
chmod: cannot access '/usr/local/bin/auto-cpufreq': No such file or directory
chmod: cannot access '/usr/local/bin/auto-cpufreq-gtk': No such file or directory
Error on file "scripts/auto-cpufreq-gtk.desktop": No such file or directory


──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────


auto-cpufreq tool successfully installed.

For list of options, run:
auto-cpufreq --help"

```
---

### System information:

Add/paste output of:

```
auto-cpufreq --debug
```

Also please be descriptive about the issue you're reporting, i.e: what you tried & what's the expected behaviour.

---
I tried to update to 1.9.9 using auto-cpufreq-installer --update from /usr/local/src/auto-cpufreq.
It removed the older version and deleted the local source tree then failed leaving absolutely nothing behind even though it reported a successful installation. 
This is a Debian trixie/sid install, nothing particularly unusual about any of it.

**Comment by shadeyg56** [comment]
Thanks for pointing this out. I used the wrong name for one of the packages that Debian requires.

Fixed with 4628b5d 

You can either pull the latest changes from master or run `sudo apt install libgtk-3-dev` then run the installer script to resolve the issue. This fix will also go out in the next release
