### ISSUE TITLE
AUR dependency error

### ISSUE THREAD

**Issue by CRAG666** [AdnanHodzic/auto-cpufreq#699]
Traceback (most recent call last):
  File "/usr/bin/auto-cpufreq", line 5, in <module>
    from auto_cpufreq.bin.auto_cpufreq import main
  File "/usr/lib/python3.12/site-packages/auto_cpufreq/bin/auto_cpufreq.py", line 14, in <module>
    from auto_cpufreq.core import *
  File "/usr/lib/python3.12/site-packages/auto_cpufreq/core.py", line 29, in <module>
    from auto_cpufreq.utils.config import config
  File "/usr/lib/python3.12/site-packages/auto_cpufreq/utils/config.py", line 2, in <module>
    from auto_cpufreq.utils.config_event_handler import ConfigEventHandler
  File "/usr/lib/python3.12/site-packages/auto_cpufreq/utils/config_event_handler.py", line 1, in <module>
    import pyinotify
ModuleNotFoundError: No module named 'pyinotify'

**Comment by Ab3loth** [comment]
paru -S python-pyinotify

needs to be added as a dependency to the aur package at some point as well but that's whats missing

**Comment by shadeyg56** [comment]
@parmjotsinghrobot @MusicalArtist12 could one of you guys help with this?

**Comment by MusicalArtist12** [comment]
Yeah we need to add python-pyinotify as a dependency

**Comment by MusicalArtist12** [comment]
`pacman -S python-pyinotify`
